name: onboarding
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dynamic_widget:
    path: ./lib/dynamic_widget
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  get: 4.6.5
  optimized_cached_image: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
